# Generated by Django 3.0 on 2019-12-23 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20191223_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_info',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient_info',
            name='paramedic',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.paramedic_info'),
        ),
    ]
