# Generated by Django 3.0 on 2019-12-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20191223_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_info',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
