# Generated by Django 3.0 on 2020-01-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20191223_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_info',
            name='birthday',
            field=models.CharField(default='2000-01-01', max_length=50),
        ),
    ]
