# Generated by Django 3.0 on 2020-01-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_patient_info_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_info',
            name='birthday',
            field=models.CharField(max_length=50),
        ),
    ]
