# Generated by Django 3.0 on 2020-01-09 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200105_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='moca_test',
            fields=[
                ('mocaTestId', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('contest', models.TextField()),
                ('result', models.TextField()),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.doctor_info')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.patient_info')),
            ],
        ),
        migrations.DeleteModel(
            name='diagnosis_info',
        ),
    ]
