# Generated by Django 3.0 on 2020-01-10 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20200109_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='moca_test',
            name='q3_2_checkbox',
            field=models.TextField(null=True),
        ),
    ]
