# Generated by Django 3.0 on 2020-01-11 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_moca_test_q3_2_checkbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient_diease',
            fields=[
                ('patientDieaseId', models.AutoField(primary_key=True, serialize=False)),
                ('symptom', models.TextField(null=True)),
                ('others', models.TextField(null=True)),
                ('date', models.CharField(max_length=50)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.patient_info')),
            ],
        ),
    ]
